package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class GdHzuserDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.companys
     *
     * @mbg.generated
     */
    private String companys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.orderNo
     *
     * @mbg.generated
     */
    private Integer orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.typeCn
     *
     * @mbg.generated
     */
    private String typecn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_hzuser_detail.typeEn
     *
     * @mbg.generated
     */
    private String typeen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gd_hzuser_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.id
     *
     * @return the value of gd_hzuser_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.id
     *
     * @param id the value for gd_hzuser_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.companys
     *
     * @return the value of gd_hzuser_detail.companys
     *
     * @mbg.generated
     */
    public String getCompanys() {
        return companys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.companys
     *
     * @param companys the value for gd_hzuser_detail.companys
     *
     * @mbg.generated
     */
    public void setCompanys(String companys) {
        this.companys = companys == null ? null : companys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.createTime
     *
     * @return the value of gd_hzuser_detail.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.createTime
     *
     * @param createtime the value for gd_hzuser_detail.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.deleted
     *
     * @return the value of gd_hzuser_detail.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.deleted
     *
     * @param deleted the value for gd_hzuser_detail.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.detail
     *
     * @return the value of gd_hzuser_detail.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.detail
     *
     * @param detail the value for gd_hzuser_detail.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.logo
     *
     * @return the value of gd_hzuser_detail.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.logo
     *
     * @param logo the value for gd_hzuser_detail.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.orderNo
     *
     * @return the value of gd_hzuser_detail.orderNo
     *
     * @mbg.generated
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.orderNo
     *
     * @param orderno the value for gd_hzuser_detail.orderNo
     *
     * @mbg.generated
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.typeCn
     *
     * @return the value of gd_hzuser_detail.typeCn
     *
     * @mbg.generated
     */
    public String getTypecn() {
        return typecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.typeCn
     *
     * @param typecn the value for gd_hzuser_detail.typeCn
     *
     * @mbg.generated
     */
    public void setTypecn(String typecn) {
        this.typecn = typecn == null ? null : typecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_hzuser_detail.typeEn
     *
     * @return the value of gd_hzuser_detail.typeEn
     *
     * @mbg.generated
     */
    public String getTypeen() {
        return typeen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_hzuser_detail.typeEn
     *
     * @param typeen the value for gd_hzuser_detail.typeEn
     *
     * @mbg.generated
     */
    public void setTypeen(String typeen) {
        this.typeen = typeen == null ? null : typeen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_hzuser_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companys=").append(companys);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", detail=").append(detail);
        sb.append(", logo=").append(logo);
        sb.append(", orderno=").append(orderno);
        sb.append(", typecn=").append(typecn);
        sb.append(", typeen=").append(typeen);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}