package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class GoldenProjectKaipiao implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.bankNo
     *
     * @mbg.generated
     */
    private String bankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.content
     *
     * @mbg.generated
     */
    private Integer content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.count
     *
     * @mbg.generated
     */
    private Double count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.createUser
     *
     * @mbg.generated
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.fpNo
     *
     * @mbg.generated
     */
    private String fpno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.fpType
     *
     * @mbg.generated
     */
    private Integer fptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.ggxh
     *
     * @mbg.generated
     */
    private String ggxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.projectId
     *
     * @mbg.generated
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.sys_createTime
     *
     * @mbg.generated
     */
    private Date sysCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.sys_createUserId
     *
     * @mbg.generated
     */
    private String sysCreateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.telNo
     *
     * @mbg.generated
     */
    private String telno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.total
     *
     * @mbg.generated
     */
    private Double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.unit
     *
     * @mbg.generated
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.bcRemark
     *
     * @mbg.generated
     */
    private String bcremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.gpDate
     *
     * @mbg.generated
     */
    private Date gpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.jsUser
     *
     * @mbg.generated
     */
    private String jsuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.kpDate
     *
     * @mbg.generated
     */
    private Date kpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.kpUser
     *
     * @mbg.generated
     */
    private String kpuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.sbNo
     *
     * @mbg.generated
     */
    private String sbno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.xxse
     *
     * @mbg.generated
     */
    private Double xxse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.htId
     *
     * @mbg.generated
     */
    private Integer htid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.hkDate
     *
     * @mbg.generated
     */
    private Date hkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.hkRemark
     *
     * @mbg.generated
     */
    private String hkremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.yue
     *
     * @mbg.generated
     */
    private Double yue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.ysk
     *
     * @mbg.generated
     */
    private Double ysk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.checkState
     *
     * @mbg.generated
     */
    private Integer checkstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.createOrganCode
     *
     * @mbg.generated
     */
    private String createorgancode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.sys_createDepartmentId
     *
     * @mbg.generated
     */
    private Integer sysCreatedepartmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_kaipiao.jine
     *
     * @mbg.generated
     */
    private Double jine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table golden_project_kaipiao
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.id
     *
     * @return the value of golden_project_kaipiao.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.id
     *
     * @param id the value for golden_project_kaipiao.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.address
     *
     * @return the value of golden_project_kaipiao.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.address
     *
     * @param address the value for golden_project_kaipiao.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.bank
     *
     * @return the value of golden_project_kaipiao.bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.bank
     *
     * @param bank the value for golden_project_kaipiao.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.bankNo
     *
     * @return the value of golden_project_kaipiao.bankNo
     *
     * @mbg.generated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.bankNo
     *
     * @param bankno the value for golden_project_kaipiao.bankNo
     *
     * @mbg.generated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.company
     *
     * @return the value of golden_project_kaipiao.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.company
     *
     * @param company the value for golden_project_kaipiao.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.content
     *
     * @return the value of golden_project_kaipiao.content
     *
     * @mbg.generated
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.content
     *
     * @param content the value for golden_project_kaipiao.content
     *
     * @mbg.generated
     */
    public void setContent(Integer content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.count
     *
     * @return the value of golden_project_kaipiao.count
     *
     * @mbg.generated
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.count
     *
     * @param count the value for golden_project_kaipiao.count
     *
     * @mbg.generated
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.createTime
     *
     * @return the value of golden_project_kaipiao.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.createTime
     *
     * @param createtime the value for golden_project_kaipiao.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.createUser
     *
     * @return the value of golden_project_kaipiao.createUser
     *
     * @mbg.generated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.createUser
     *
     * @param createuser the value for golden_project_kaipiao.createUser
     *
     * @mbg.generated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.fpNo
     *
     * @return the value of golden_project_kaipiao.fpNo
     *
     * @mbg.generated
     */
    public String getFpno() {
        return fpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.fpNo
     *
     * @param fpno the value for golden_project_kaipiao.fpNo
     *
     * @mbg.generated
     */
    public void setFpno(String fpno) {
        this.fpno = fpno == null ? null : fpno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.fpType
     *
     * @return the value of golden_project_kaipiao.fpType
     *
     * @mbg.generated
     */
    public Integer getFptype() {
        return fptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.fpType
     *
     * @param fptype the value for golden_project_kaipiao.fpType
     *
     * @mbg.generated
     */
    public void setFptype(Integer fptype) {
        this.fptype = fptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.ggxh
     *
     * @return the value of golden_project_kaipiao.ggxh
     *
     * @mbg.generated
     */
    public String getGgxh() {
        return ggxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.ggxh
     *
     * @param ggxh the value for golden_project_kaipiao.ggxh
     *
     * @mbg.generated
     */
    public void setGgxh(String ggxh) {
        this.ggxh = ggxh == null ? null : ggxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.price
     *
     * @return the value of golden_project_kaipiao.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.price
     *
     * @param price the value for golden_project_kaipiao.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.projectId
     *
     * @return the value of golden_project_kaipiao.projectId
     *
     * @mbg.generated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.projectId
     *
     * @param projectid the value for golden_project_kaipiao.projectId
     *
     * @mbg.generated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.remark
     *
     * @return the value of golden_project_kaipiao.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.remark
     *
     * @param remark the value for golden_project_kaipiao.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.sys_createTime
     *
     * @return the value of golden_project_kaipiao.sys_createTime
     *
     * @mbg.generated
     */
    public Date getSysCreatetime() {
        return sysCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.sys_createTime
     *
     * @param sysCreatetime the value for golden_project_kaipiao.sys_createTime
     *
     * @mbg.generated
     */
    public void setSysCreatetime(Date sysCreatetime) {
        this.sysCreatetime = sysCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.sys_createUserId
     *
     * @return the value of golden_project_kaipiao.sys_createUserId
     *
     * @mbg.generated
     */
    public String getSysCreateuserid() {
        return sysCreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.sys_createUserId
     *
     * @param sysCreateuserid the value for golden_project_kaipiao.sys_createUserId
     *
     * @mbg.generated
     */
    public void setSysCreateuserid(String sysCreateuserid) {
        this.sysCreateuserid = sysCreateuserid == null ? null : sysCreateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.telNo
     *
     * @return the value of golden_project_kaipiao.telNo
     *
     * @mbg.generated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.telNo
     *
     * @param telno the value for golden_project_kaipiao.telNo
     *
     * @mbg.generated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.total
     *
     * @return the value of golden_project_kaipiao.total
     *
     * @mbg.generated
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.total
     *
     * @param total the value for golden_project_kaipiao.total
     *
     * @mbg.generated
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.unit
     *
     * @return the value of golden_project_kaipiao.unit
     *
     * @mbg.generated
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.unit
     *
     * @param unit the value for golden_project_kaipiao.unit
     *
     * @mbg.generated
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.bcRemark
     *
     * @return the value of golden_project_kaipiao.bcRemark
     *
     * @mbg.generated
     */
    public String getBcremark() {
        return bcremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.bcRemark
     *
     * @param bcremark the value for golden_project_kaipiao.bcRemark
     *
     * @mbg.generated
     */
    public void setBcremark(String bcremark) {
        this.bcremark = bcremark == null ? null : bcremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.gpDate
     *
     * @return the value of golden_project_kaipiao.gpDate
     *
     * @mbg.generated
     */
    public Date getGpdate() {
        return gpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.gpDate
     *
     * @param gpdate the value for golden_project_kaipiao.gpDate
     *
     * @mbg.generated
     */
    public void setGpdate(Date gpdate) {
        this.gpdate = gpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.jsUser
     *
     * @return the value of golden_project_kaipiao.jsUser
     *
     * @mbg.generated
     */
    public String getJsuser() {
        return jsuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.jsUser
     *
     * @param jsuser the value for golden_project_kaipiao.jsUser
     *
     * @mbg.generated
     */
    public void setJsuser(String jsuser) {
        this.jsuser = jsuser == null ? null : jsuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.kpDate
     *
     * @return the value of golden_project_kaipiao.kpDate
     *
     * @mbg.generated
     */
    public Date getKpdate() {
        return kpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.kpDate
     *
     * @param kpdate the value for golden_project_kaipiao.kpDate
     *
     * @mbg.generated
     */
    public void setKpdate(Date kpdate) {
        this.kpdate = kpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.kpUser
     *
     * @return the value of golden_project_kaipiao.kpUser
     *
     * @mbg.generated
     */
    public String getKpuser() {
        return kpuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.kpUser
     *
     * @param kpuser the value for golden_project_kaipiao.kpUser
     *
     * @mbg.generated
     */
    public void setKpuser(String kpuser) {
        this.kpuser = kpuser == null ? null : kpuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.sbNo
     *
     * @return the value of golden_project_kaipiao.sbNo
     *
     * @mbg.generated
     */
    public String getSbno() {
        return sbno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.sbNo
     *
     * @param sbno the value for golden_project_kaipiao.sbNo
     *
     * @mbg.generated
     */
    public void setSbno(String sbno) {
        this.sbno = sbno == null ? null : sbno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.xxse
     *
     * @return the value of golden_project_kaipiao.xxse
     *
     * @mbg.generated
     */
    public Double getXxse() {
        return xxse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.xxse
     *
     * @param xxse the value for golden_project_kaipiao.xxse
     *
     * @mbg.generated
     */
    public void setXxse(Double xxse) {
        this.xxse = xxse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.htId
     *
     * @return the value of golden_project_kaipiao.htId
     *
     * @mbg.generated
     */
    public Integer getHtid() {
        return htid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.htId
     *
     * @param htid the value for golden_project_kaipiao.htId
     *
     * @mbg.generated
     */
    public void setHtid(Integer htid) {
        this.htid = htid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.hkDate
     *
     * @return the value of golden_project_kaipiao.hkDate
     *
     * @mbg.generated
     */
    public Date getHkdate() {
        return hkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.hkDate
     *
     * @param hkdate the value for golden_project_kaipiao.hkDate
     *
     * @mbg.generated
     */
    public void setHkdate(Date hkdate) {
        this.hkdate = hkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.hkRemark
     *
     * @return the value of golden_project_kaipiao.hkRemark
     *
     * @mbg.generated
     */
    public String getHkremark() {
        return hkremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.hkRemark
     *
     * @param hkremark the value for golden_project_kaipiao.hkRemark
     *
     * @mbg.generated
     */
    public void setHkremark(String hkremark) {
        this.hkremark = hkremark == null ? null : hkremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.yue
     *
     * @return the value of golden_project_kaipiao.yue
     *
     * @mbg.generated
     */
    public Double getYue() {
        return yue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.yue
     *
     * @param yue the value for golden_project_kaipiao.yue
     *
     * @mbg.generated
     */
    public void setYue(Double yue) {
        this.yue = yue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.ysk
     *
     * @return the value of golden_project_kaipiao.ysk
     *
     * @mbg.generated
     */
    public Double getYsk() {
        return ysk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.ysk
     *
     * @param ysk the value for golden_project_kaipiao.ysk
     *
     * @mbg.generated
     */
    public void setYsk(Double ysk) {
        this.ysk = ysk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.checkState
     *
     * @return the value of golden_project_kaipiao.checkState
     *
     * @mbg.generated
     */
    public Integer getCheckstate() {
        return checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.checkState
     *
     * @param checkstate the value for golden_project_kaipiao.checkState
     *
     * @mbg.generated
     */
    public void setCheckstate(Integer checkstate) {
        this.checkstate = checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.createOrganCode
     *
     * @return the value of golden_project_kaipiao.createOrganCode
     *
     * @mbg.generated
     */
    public String getCreateorgancode() {
        return createorgancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.createOrganCode
     *
     * @param createorgancode the value for golden_project_kaipiao.createOrganCode
     *
     * @mbg.generated
     */
    public void setCreateorgancode(String createorgancode) {
        this.createorgancode = createorgancode == null ? null : createorgancode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.sys_createDepartmentId
     *
     * @return the value of golden_project_kaipiao.sys_createDepartmentId
     *
     * @mbg.generated
     */
    public Integer getSysCreatedepartmentid() {
        return sysCreatedepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.sys_createDepartmentId
     *
     * @param sysCreatedepartmentid the value for golden_project_kaipiao.sys_createDepartmentId
     *
     * @mbg.generated
     */
    public void setSysCreatedepartmentid(Integer sysCreatedepartmentid) {
        this.sysCreatedepartmentid = sysCreatedepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.type
     *
     * @return the value of golden_project_kaipiao.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.type
     *
     * @param type the value for golden_project_kaipiao.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_kaipiao.jine
     *
     * @return the value of golden_project_kaipiao.jine
     *
     * @mbg.generated
     */
    public Double getJine() {
        return jine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_kaipiao.jine
     *
     * @param jine the value for golden_project_kaipiao.jine
     *
     * @mbg.generated
     */
    public void setJine(Double jine) {
        this.jine = jine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_kaipiao
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", bank=").append(bank);
        sb.append(", bankno=").append(bankno);
        sb.append(", company=").append(company);
        sb.append(", content=").append(content);
        sb.append(", count=").append(count);
        sb.append(", createtime=").append(createtime);
        sb.append(", createuser=").append(createuser);
        sb.append(", fpno=").append(fpno);
        sb.append(", fptype=").append(fptype);
        sb.append(", ggxh=").append(ggxh);
        sb.append(", price=").append(price);
        sb.append(", projectid=").append(projectid);
        sb.append(", remark=").append(remark);
        sb.append(", sysCreatetime=").append(sysCreatetime);
        sb.append(", sysCreateuserid=").append(sysCreateuserid);
        sb.append(", telno=").append(telno);
        sb.append(", total=").append(total);
        sb.append(", unit=").append(unit);
        sb.append(", bcremark=").append(bcremark);
        sb.append(", gpdate=").append(gpdate);
        sb.append(", jsuser=").append(jsuser);
        sb.append(", kpdate=").append(kpdate);
        sb.append(", kpuser=").append(kpuser);
        sb.append(", sbno=").append(sbno);
        sb.append(", xxse=").append(xxse);
        sb.append(", htid=").append(htid);
        sb.append(", hkdate=").append(hkdate);
        sb.append(", hkremark=").append(hkremark);
        sb.append(", yue=").append(yue);
        sb.append(", ysk=").append(ysk);
        sb.append(", checkstate=").append(checkstate);
        sb.append(", createorgancode=").append(createorgancode);
        sb.append(", sysCreatedepartmentid=").append(sysCreatedepartmentid);
        sb.append(", type=").append(type);
        sb.append(", jine=").append(jine);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}