package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class GoldenMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.createUser
     *
     * @mbg.generated
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.createUserId
     *
     * @mbg.generated
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.departmentId
     *
     * @mbg.generated
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.departmentName
     *
     * @mbg.generated
     */
    private String departmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.proNo
     *
     * @mbg.generated
     */
    private String prono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.proId
     *
     * @mbg.generated
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.receiveUser
     *
     * @mbg.generated
     */
    private String receiveuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.createUserAndName
     *
     * @mbg.generated
     */
    private String createuserandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_message.typeMsg
     *
     * @mbg.generated
     */
    private Integer typemsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table golden_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.id
     *
     * @return the value of golden_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.id
     *
     * @param id the value for golden_message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.createTime
     *
     * @return the value of golden_message.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.createTime
     *
     * @param createtime the value for golden_message.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.createUser
     *
     * @return the value of golden_message.createUser
     *
     * @mbg.generated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.createUser
     *
     * @param createuser the value for golden_message.createUser
     *
     * @mbg.generated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.createUserId
     *
     * @return the value of golden_message.createUserId
     *
     * @mbg.generated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.createUserId
     *
     * @param createuserid the value for golden_message.createUserId
     *
     * @mbg.generated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.deleted
     *
     * @return the value of golden_message.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.deleted
     *
     * @param deleted the value for golden_message.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.departmentId
     *
     * @return the value of golden_message.departmentId
     *
     * @mbg.generated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.departmentId
     *
     * @param departmentid the value for golden_message.departmentId
     *
     * @mbg.generated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.departmentName
     *
     * @return the value of golden_message.departmentName
     *
     * @mbg.generated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.departmentName
     *
     * @param departmentname the value for golden_message.departmentName
     *
     * @mbg.generated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.proNo
     *
     * @return the value of golden_message.proNo
     *
     * @mbg.generated
     */
    public String getProno() {
        return prono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.proNo
     *
     * @param prono the value for golden_message.proNo
     *
     * @mbg.generated
     */
    public void setProno(String prono) {
        this.prono = prono == null ? null : prono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.state
     *
     * @return the value of golden_message.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.state
     *
     * @param state the value for golden_message.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.title
     *
     * @return the value of golden_message.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.title
     *
     * @param title the value for golden_message.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.type
     *
     * @return the value of golden_message.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.type
     *
     * @param type the value for golden_message.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.proId
     *
     * @return the value of golden_message.proId
     *
     * @mbg.generated
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.proId
     *
     * @param proid the value for golden_message.proId
     *
     * @mbg.generated
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.receiveUser
     *
     * @return the value of golden_message.receiveUser
     *
     * @mbg.generated
     */
    public String getReceiveuser() {
        return receiveuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.receiveUser
     *
     * @param receiveuser the value for golden_message.receiveUser
     *
     * @mbg.generated
     */
    public void setReceiveuser(String receiveuser) {
        this.receiveuser = receiveuser == null ? null : receiveuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.createUserAndName
     *
     * @return the value of golden_message.createUserAndName
     *
     * @mbg.generated
     */
    public String getCreateuserandname() {
        return createuserandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.createUserAndName
     *
     * @param createuserandname the value for golden_message.createUserAndName
     *
     * @mbg.generated
     */
    public void setCreateuserandname(String createuserandname) {
        this.createuserandname = createuserandname == null ? null : createuserandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_message.typeMsg
     *
     * @return the value of golden_message.typeMsg
     *
     * @mbg.generated
     */
    public Integer getTypemsg() {
        return typemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_message.typeMsg
     *
     * @param typemsg the value for golden_message.typeMsg
     *
     * @mbg.generated
     */
    public void setTypemsg(Integer typemsg) {
        this.typemsg = typemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_message
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createtime=").append(createtime);
        sb.append(", createuser=").append(createuser);
        sb.append(", createuserid=").append(createuserid);
        sb.append(", deleted=").append(deleted);
        sb.append(", departmentid=").append(departmentid);
        sb.append(", departmentname=").append(departmentname);
        sb.append(", prono=").append(prono);
        sb.append(", state=").append(state);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", proid=").append(proid);
        sb.append(", receiveuser=").append(receiveuser);
        sb.append(", createuserandname=").append(createuserandname);
        sb.append(", typemsg=").append(typemsg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}