package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class GoldenProjectSq implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.bcount
     *
     * @mbg.generated
     */
    private String bcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.createUser
     *
     * @mbg.generated
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.departmentId
     *
     * @mbg.generated
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.departmentName
     *
     * @mbg.generated
     */
    private String departmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.hszcount
     *
     * @mbg.generated
     */
    private String hszcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.jsdcount
     *
     * @mbg.generated
     */
    private String jsdcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.product
     *
     * @mbg.generated
     */
    private Integer product;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.projectId
     *
     * @mbg.generated
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.strcount
     *
     * @mbg.generated
     */
    private String strcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.sys_createTime
     *
     * @mbg.generated
     */
    private Date sysCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.sys_createUserId
     *
     * @mbg.generated
     */
    private String sysCreateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.usercount
     *
     * @mbg.generated
     */
    private String usercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.wjcount
     *
     * @mbg.generated
     */
    private String wjcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.xzDate
     *
     * @mbg.generated
     */
    private Date xzdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.macjqm
     *
     * @mbg.generated
     */
    private String macjqm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.makeTime
     *
     * @mbg.generated
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.makeUser
     *
     * @mbg.generated
     */
    private String makeuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.receiveCompany
     *
     * @mbg.generated
     */
    private String receivecompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.receivePeople
     *
     * @mbg.generated
     */
    private String receivepeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.sendTime
     *
     * @mbg.generated
     */
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.sendType
     *
     * @mbg.generated
     */
    private Integer sendtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.sendUser
     *
     * @mbg.generated
     */
    private String senduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.telNo
     *
     * @mbg.generated
     */
    private String telno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.downCount
     *
     * @mbg.generated
     */
    private Integer downcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.checkState
     *
     * @mbg.generated
     */
    private Integer checkstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.createOrganCode
     *
     * @mbg.generated
     */
    private String createorgancode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.dcount
     *
     * @mbg.generated
     */
    private Integer dcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_project_sq.lastUser
     *
     * @mbg.generated
     */
    private String lastuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table golden_project_sq
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.id
     *
     * @return the value of golden_project_sq.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.id
     *
     * @param id the value for golden_project_sq.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.bcount
     *
     * @return the value of golden_project_sq.bcount
     *
     * @mbg.generated
     */
    public String getBcount() {
        return bcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.bcount
     *
     * @param bcount the value for golden_project_sq.bcount
     *
     * @mbg.generated
     */
    public void setBcount(String bcount) {
        this.bcount = bcount == null ? null : bcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.createTime
     *
     * @return the value of golden_project_sq.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.createTime
     *
     * @param createtime the value for golden_project_sq.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.createUser
     *
     * @return the value of golden_project_sq.createUser
     *
     * @mbg.generated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.createUser
     *
     * @param createuser the value for golden_project_sq.createUser
     *
     * @mbg.generated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.departmentId
     *
     * @return the value of golden_project_sq.departmentId
     *
     * @mbg.generated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.departmentId
     *
     * @param departmentid the value for golden_project_sq.departmentId
     *
     * @mbg.generated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.departmentName
     *
     * @return the value of golden_project_sq.departmentName
     *
     * @mbg.generated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.departmentName
     *
     * @param departmentname the value for golden_project_sq.departmentName
     *
     * @mbg.generated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.hszcount
     *
     * @return the value of golden_project_sq.hszcount
     *
     * @mbg.generated
     */
    public String getHszcount() {
        return hszcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.hszcount
     *
     * @param hszcount the value for golden_project_sq.hszcount
     *
     * @mbg.generated
     */
    public void setHszcount(String hszcount) {
        this.hszcount = hszcount == null ? null : hszcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.jsdcount
     *
     * @return the value of golden_project_sq.jsdcount
     *
     * @mbg.generated
     */
    public String getJsdcount() {
        return jsdcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.jsdcount
     *
     * @param jsdcount the value for golden_project_sq.jsdcount
     *
     * @mbg.generated
     */
    public void setJsdcount(String jsdcount) {
        this.jsdcount = jsdcount == null ? null : jsdcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.product
     *
     * @return the value of golden_project_sq.product
     *
     * @mbg.generated
     */
    public Integer getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.product
     *
     * @param product the value for golden_project_sq.product
     *
     * @mbg.generated
     */
    public void setProduct(Integer product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.projectId
     *
     * @return the value of golden_project_sq.projectId
     *
     * @mbg.generated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.projectId
     *
     * @param projectid the value for golden_project_sq.projectId
     *
     * @mbg.generated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.strcount
     *
     * @return the value of golden_project_sq.strcount
     *
     * @mbg.generated
     */
    public String getStrcount() {
        return strcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.strcount
     *
     * @param strcount the value for golden_project_sq.strcount
     *
     * @mbg.generated
     */
    public void setStrcount(String strcount) {
        this.strcount = strcount == null ? null : strcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.sys_createTime
     *
     * @return the value of golden_project_sq.sys_createTime
     *
     * @mbg.generated
     */
    public Date getSysCreatetime() {
        return sysCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.sys_createTime
     *
     * @param sysCreatetime the value for golden_project_sq.sys_createTime
     *
     * @mbg.generated
     */
    public void setSysCreatetime(Date sysCreatetime) {
        this.sysCreatetime = sysCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.sys_createUserId
     *
     * @return the value of golden_project_sq.sys_createUserId
     *
     * @mbg.generated
     */
    public String getSysCreateuserid() {
        return sysCreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.sys_createUserId
     *
     * @param sysCreateuserid the value for golden_project_sq.sys_createUserId
     *
     * @mbg.generated
     */
    public void setSysCreateuserid(String sysCreateuserid) {
        this.sysCreateuserid = sysCreateuserid == null ? null : sysCreateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.usercount
     *
     * @return the value of golden_project_sq.usercount
     *
     * @mbg.generated
     */
    public String getUsercount() {
        return usercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.usercount
     *
     * @param usercount the value for golden_project_sq.usercount
     *
     * @mbg.generated
     */
    public void setUsercount(String usercount) {
        this.usercount = usercount == null ? null : usercount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.version
     *
     * @return the value of golden_project_sq.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.version
     *
     * @param version the value for golden_project_sq.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.wjcount
     *
     * @return the value of golden_project_sq.wjcount
     *
     * @mbg.generated
     */
    public String getWjcount() {
        return wjcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.wjcount
     *
     * @param wjcount the value for golden_project_sq.wjcount
     *
     * @mbg.generated
     */
    public void setWjcount(String wjcount) {
        this.wjcount = wjcount == null ? null : wjcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.xzDate
     *
     * @return the value of golden_project_sq.xzDate
     *
     * @mbg.generated
     */
    public Date getXzdate() {
        return xzdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.xzDate
     *
     * @param xzdate the value for golden_project_sq.xzDate
     *
     * @mbg.generated
     */
    public void setXzdate(Date xzdate) {
        this.xzdate = xzdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.macjqm
     *
     * @return the value of golden_project_sq.macjqm
     *
     * @mbg.generated
     */
    public String getMacjqm() {
        return macjqm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.macjqm
     *
     * @param macjqm the value for golden_project_sq.macjqm
     *
     * @mbg.generated
     */
    public void setMacjqm(String macjqm) {
        this.macjqm = macjqm == null ? null : macjqm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.type
     *
     * @return the value of golden_project_sq.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.type
     *
     * @param type the value for golden_project_sq.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.state
     *
     * @return the value of golden_project_sq.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.state
     *
     * @param state the value for golden_project_sq.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.makeTime
     *
     * @return the value of golden_project_sq.makeTime
     *
     * @mbg.generated
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.makeTime
     *
     * @param maketime the value for golden_project_sq.makeTime
     *
     * @mbg.generated
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.makeUser
     *
     * @return the value of golden_project_sq.makeUser
     *
     * @mbg.generated
     */
    public String getMakeuser() {
        return makeuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.makeUser
     *
     * @param makeuser the value for golden_project_sq.makeUser
     *
     * @mbg.generated
     */
    public void setMakeuser(String makeuser) {
        this.makeuser = makeuser == null ? null : makeuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.receiveCompany
     *
     * @return the value of golden_project_sq.receiveCompany
     *
     * @mbg.generated
     */
    public String getReceivecompany() {
        return receivecompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.receiveCompany
     *
     * @param receivecompany the value for golden_project_sq.receiveCompany
     *
     * @mbg.generated
     */
    public void setReceivecompany(String receivecompany) {
        this.receivecompany = receivecompany == null ? null : receivecompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.receivePeople
     *
     * @return the value of golden_project_sq.receivePeople
     *
     * @mbg.generated
     */
    public String getReceivepeople() {
        return receivepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.receivePeople
     *
     * @param receivepeople the value for golden_project_sq.receivePeople
     *
     * @mbg.generated
     */
    public void setReceivepeople(String receivepeople) {
        this.receivepeople = receivepeople == null ? null : receivepeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.sendTime
     *
     * @return the value of golden_project_sq.sendTime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.sendTime
     *
     * @param sendtime the value for golden_project_sq.sendTime
     *
     * @mbg.generated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.sendType
     *
     * @return the value of golden_project_sq.sendType
     *
     * @mbg.generated
     */
    public Integer getSendtype() {
        return sendtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.sendType
     *
     * @param sendtype the value for golden_project_sq.sendType
     *
     * @mbg.generated
     */
    public void setSendtype(Integer sendtype) {
        this.sendtype = sendtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.sendUser
     *
     * @return the value of golden_project_sq.sendUser
     *
     * @mbg.generated
     */
    public String getSenduser() {
        return senduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.sendUser
     *
     * @param senduser the value for golden_project_sq.sendUser
     *
     * @mbg.generated
     */
    public void setSenduser(String senduser) {
        this.senduser = senduser == null ? null : senduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.telNo
     *
     * @return the value of golden_project_sq.telNo
     *
     * @mbg.generated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.telNo
     *
     * @param telno the value for golden_project_sq.telNo
     *
     * @mbg.generated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.remark
     *
     * @return the value of golden_project_sq.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.remark
     *
     * @param remark the value for golden_project_sq.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.deleted
     *
     * @return the value of golden_project_sq.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.deleted
     *
     * @param deleted the value for golden_project_sq.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.downCount
     *
     * @return the value of golden_project_sq.downCount
     *
     * @mbg.generated
     */
    public Integer getDowncount() {
        return downcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.downCount
     *
     * @param downcount the value for golden_project_sq.downCount
     *
     * @mbg.generated
     */
    public void setDowncount(Integer downcount) {
        this.downcount = downcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.checkState
     *
     * @return the value of golden_project_sq.checkState
     *
     * @mbg.generated
     */
    public Integer getCheckstate() {
        return checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.checkState
     *
     * @param checkstate the value for golden_project_sq.checkState
     *
     * @mbg.generated
     */
    public void setCheckstate(Integer checkstate) {
        this.checkstate = checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.createOrganCode
     *
     * @return the value of golden_project_sq.createOrganCode
     *
     * @mbg.generated
     */
    public String getCreateorgancode() {
        return createorgancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.createOrganCode
     *
     * @param createorgancode the value for golden_project_sq.createOrganCode
     *
     * @mbg.generated
     */
    public void setCreateorgancode(String createorgancode) {
        this.createorgancode = createorgancode == null ? null : createorgancode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.dcount
     *
     * @return the value of golden_project_sq.dcount
     *
     * @mbg.generated
     */
    public Integer getDcount() {
        return dcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.dcount
     *
     * @param dcount the value for golden_project_sq.dcount
     *
     * @mbg.generated
     */
    public void setDcount(Integer dcount) {
        this.dcount = dcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_project_sq.lastUser
     *
     * @return the value of golden_project_sq.lastUser
     *
     * @mbg.generated
     */
    public String getLastuser() {
        return lastuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_project_sq.lastUser
     *
     * @param lastuser the value for golden_project_sq.lastUser
     *
     * @mbg.generated
     */
    public void setLastuser(String lastuser) {
        this.lastuser = lastuser == null ? null : lastuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_sq
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bcount=").append(bcount);
        sb.append(", createtime=").append(createtime);
        sb.append(", createuser=").append(createuser);
        sb.append(", departmentid=").append(departmentid);
        sb.append(", departmentname=").append(departmentname);
        sb.append(", hszcount=").append(hszcount);
        sb.append(", jsdcount=").append(jsdcount);
        sb.append(", product=").append(product);
        sb.append(", projectid=").append(projectid);
        sb.append(", strcount=").append(strcount);
        sb.append(", sysCreatetime=").append(sysCreatetime);
        sb.append(", sysCreateuserid=").append(sysCreateuserid);
        sb.append(", usercount=").append(usercount);
        sb.append(", version=").append(version);
        sb.append(", wjcount=").append(wjcount);
        sb.append(", xzdate=").append(xzdate);
        sb.append(", macjqm=").append(macjqm);
        sb.append(", type=").append(type);
        sb.append(", state=").append(state);
        sb.append(", maketime=").append(maketime);
        sb.append(", makeuser=").append(makeuser);
        sb.append(", receivecompany=").append(receivecompany);
        sb.append(", receivepeople=").append(receivepeople);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", sendtype=").append(sendtype);
        sb.append(", senduser=").append(senduser);
        sb.append(", telno=").append(telno);
        sb.append(", remark=").append(remark);
        sb.append(", deleted=").append(deleted);
        sb.append(", downcount=").append(downcount);
        sb.append(", checkstate=").append(checkstate);
        sb.append(", createorgancode=").append(createorgancode);
        sb.append(", dcount=").append(dcount);
        sb.append(", lastuser=").append(lastuser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}