package com.golden.website.dataobject;

import java.io.Serializable;

public class ThAnswer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.moudle
     *
     * @mbg.generated
     */
    private String moudle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.questionId
     *
     * @mbg.generated
     */
    private Integer questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.resultTitle
     *
     * @mbg.generated
     */
    private String resulttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.userIdentity
     *
     * @mbg.generated
     */
    private String useridentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_answer.userType
     *
     * @mbg.generated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_answer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.id
     *
     * @return the value of th_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.id
     *
     * @param id the value for th_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.answer
     *
     * @return the value of th_answer.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.answer
     *
     * @param answer the value for th_answer.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.moudle
     *
     * @return the value of th_answer.moudle
     *
     * @mbg.generated
     */
    public String getMoudle() {
        return moudle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.moudle
     *
     * @param moudle the value for th_answer.moudle
     *
     * @mbg.generated
     */
    public void setMoudle(String moudle) {
        this.moudle = moudle == null ? null : moudle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.questionId
     *
     * @return the value of th_answer.questionId
     *
     * @mbg.generated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.questionId
     *
     * @param questionid the value for th_answer.questionId
     *
     * @mbg.generated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.result
     *
     * @return the value of th_answer.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.result
     *
     * @param result the value for th_answer.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.resultTitle
     *
     * @return the value of th_answer.resultTitle
     *
     * @mbg.generated
     */
    public String getResulttitle() {
        return resulttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.resultTitle
     *
     * @param resulttitle the value for th_answer.resultTitle
     *
     * @mbg.generated
     */
    public void setResulttitle(String resulttitle) {
        this.resulttitle = resulttitle == null ? null : resulttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.userIdentity
     *
     * @return the value of th_answer.userIdentity
     *
     * @mbg.generated
     */
    public String getUseridentity() {
        return useridentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.userIdentity
     *
     * @param useridentity the value for th_answer.userIdentity
     *
     * @mbg.generated
     */
    public void setUseridentity(String useridentity) {
        this.useridentity = useridentity == null ? null : useridentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_answer.userType
     *
     * @return the value of th_answer.userType
     *
     * @mbg.generated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_answer.userType
     *
     * @param usertype the value for th_answer.userType
     *
     * @mbg.generated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_answer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", answer=").append(answer);
        sb.append(", moudle=").append(moudle);
        sb.append(", questionid=").append(questionid);
        sb.append(", result=").append(result);
        sb.append(", resulttitle=").append(resulttitle);
        sb.append(", useridentity=").append(useridentity);
        sb.append(", usertype=").append(usertype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}