package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThAppMsgcode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_app_msgcode.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_app_msgcode.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_app_msgcode.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_app_msgcode.userCount
     *
     * @mbg.generated
     */
    private String usercount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_app_msgcode.id
     *
     * @return the value of th_app_msgcode.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_app_msgcode.id
     *
     * @param id the value for th_app_msgcode.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_app_msgcode.code
     *
     * @return the value of th_app_msgcode.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_app_msgcode.code
     *
     * @param code the value for th_app_msgcode.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_app_msgcode.createTime
     *
     * @return the value of th_app_msgcode.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_app_msgcode.createTime
     *
     * @param createtime the value for th_app_msgcode.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_app_msgcode.userCount
     *
     * @return the value of th_app_msgcode.userCount
     *
     * @mbg.generated
     */
    public String getUsercount() {
        return usercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_app_msgcode.userCount
     *
     * @param usercount the value for th_app_msgcode.userCount
     *
     * @mbg.generated
     */
    public void setUsercount(String usercount) {
        this.usercount = usercount == null ? null : usercount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", createtime=").append(createtime);
        sb.append(", usercount=").append(usercount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}