package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThNoticeStore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_notice_store.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_notice_store.noticeId
     *
     * @mbg.generated
     */
    private Integer noticeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_notice_store.devNo
     *
     * @mbg.generated
     */
    private String devno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_notice_store.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_notice_store.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_notice_store
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_notice_store.id
     *
     * @return the value of th_notice_store.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_notice_store.id
     *
     * @param id the value for th_notice_store.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_notice_store.noticeId
     *
     * @return the value of th_notice_store.noticeId
     *
     * @mbg.generated
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_notice_store.noticeId
     *
     * @param noticeid the value for th_notice_store.noticeId
     *
     * @mbg.generated
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_notice_store.devNo
     *
     * @return the value of th_notice_store.devNo
     *
     * @mbg.generated
     */
    public String getDevno() {
        return devno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_notice_store.devNo
     *
     * @param devno the value for th_notice_store.devNo
     *
     * @mbg.generated
     */
    public void setDevno(String devno) {
        this.devno = devno == null ? null : devno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_notice_store.deleted
     *
     * @return the value of th_notice_store.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_notice_store.deleted
     *
     * @param deleted the value for th_notice_store.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_notice_store.createTime
     *
     * @return the value of th_notice_store.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_notice_store.createTime
     *
     * @param createtime the value for th_notice_store.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_notice_store
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", noticeid=").append(noticeid);
        sb.append(", devno=").append(devno);
        sb.append(", deleted=").append(deleted);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}