package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThScoreSet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.maxscore
     *
     * @mbg.generated
     */
    private Integer maxscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.createby
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_score_set.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_score_set
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.id
     *
     * @return the value of th_score_set.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.id
     *
     * @param id the value for th_score_set.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.type
     *
     * @return the value of th_score_set.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.type
     *
     * @param type the value for th_score_set.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.score
     *
     * @return the value of th_score_set.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.score
     *
     * @param score the value for th_score_set.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.maxscore
     *
     * @return the value of th_score_set.maxscore
     *
     * @mbg.generated
     */
    public Integer getMaxscore() {
        return maxscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.maxscore
     *
     * @param maxscore the value for th_score_set.maxscore
     *
     * @mbg.generated
     */
    public void setMaxscore(Integer maxscore) {
        this.maxscore = maxscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.createTime
     *
     * @return the value of th_score_set.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.createTime
     *
     * @param createtime the value for th_score_set.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.createby
     *
     * @return the value of th_score_set.createby
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.createby
     *
     * @param createby the value for th_score_set.createby
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_score_set.deleted
     *
     * @return the value of th_score_set.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_score_set.deleted
     *
     * @param deleted the value for th_score_set.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_score_set
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", score=").append(score);
        sb.append(", maxscore=").append(maxscore);
        sb.append(", createtime=").append(createtime);
        sb.append(", createby=").append(createby);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}