package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThShopOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.buyAddress
     *
     * @mbg.generated
     */
    private String buyaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.buyCity
     *
     * @mbg.generated
     */
    private String buycity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.buyName
     *
     * @mbg.generated
     */
    private String buyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.buyPhone
     *
     * @mbg.generated
     */
    private String buyphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.buyProvince
     *
     * @mbg.generated
     */
    private String buyprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.cardId
     *
     * @mbg.generated
     */
    private String cardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.cardNo
     *
     * @mbg.generated
     */
    private String cardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.comTime
     *
     * @mbg.generated
     */
    private Date comtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.moneyCode
     *
     * @mbg.generated
     */
    private String moneycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.orderNo
     *
     * @mbg.generated
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.orderType
     *
     * @mbg.generated
     */
    private Integer ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.payTime
     *
     * @mbg.generated
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.payType
     *
     * @mbg.generated
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.postage
     *
     * @mbg.generated
     */
    private Double postage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.sendTime
     *
     * @mbg.generated
     */
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.shopId
     *
     * @mbg.generated
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.addressId
     *
     * @mbg.generated
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.receipt
     *
     * @mbg.generated
     */
    private String receipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.expressNo
     *
     * @mbg.generated
     */
    private String expressno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.sendPeo
     *
     * @mbg.generated
     */
    private String sendpeo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.expressCom
     *
     * @mbg.generated
     */
    private String expresscom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.sendRemark
     *
     * @mbg.generated
     */
    private String sendremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_order.busId
     *
     * @mbg.generated
     */
    private Integer busid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_shop_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.id
     *
     * @return the value of th_shop_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.id
     *
     * @param id the value for th_shop_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.buyAddress
     *
     * @return the value of th_shop_order.buyAddress
     *
     * @mbg.generated
     */
    public String getBuyaddress() {
        return buyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.buyAddress
     *
     * @param buyaddress the value for th_shop_order.buyAddress
     *
     * @mbg.generated
     */
    public void setBuyaddress(String buyaddress) {
        this.buyaddress = buyaddress == null ? null : buyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.buyCity
     *
     * @return the value of th_shop_order.buyCity
     *
     * @mbg.generated
     */
    public String getBuycity() {
        return buycity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.buyCity
     *
     * @param buycity the value for th_shop_order.buyCity
     *
     * @mbg.generated
     */
    public void setBuycity(String buycity) {
        this.buycity = buycity == null ? null : buycity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.buyName
     *
     * @return the value of th_shop_order.buyName
     *
     * @mbg.generated
     */
    public String getBuyname() {
        return buyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.buyName
     *
     * @param buyname the value for th_shop_order.buyName
     *
     * @mbg.generated
     */
    public void setBuyname(String buyname) {
        this.buyname = buyname == null ? null : buyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.buyPhone
     *
     * @return the value of th_shop_order.buyPhone
     *
     * @mbg.generated
     */
    public String getBuyphone() {
        return buyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.buyPhone
     *
     * @param buyphone the value for th_shop_order.buyPhone
     *
     * @mbg.generated
     */
    public void setBuyphone(String buyphone) {
        this.buyphone = buyphone == null ? null : buyphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.buyProvince
     *
     * @return the value of th_shop_order.buyProvince
     *
     * @mbg.generated
     */
    public String getBuyprovince() {
        return buyprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.buyProvince
     *
     * @param buyprovince the value for th_shop_order.buyProvince
     *
     * @mbg.generated
     */
    public void setBuyprovince(String buyprovince) {
        this.buyprovince = buyprovince == null ? null : buyprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.cardId
     *
     * @return the value of th_shop_order.cardId
     *
     * @mbg.generated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.cardId
     *
     * @param cardid the value for th_shop_order.cardId
     *
     * @mbg.generated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.cardNo
     *
     * @return the value of th_shop_order.cardNo
     *
     * @mbg.generated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.cardNo
     *
     * @param cardno the value for th_shop_order.cardNo
     *
     * @mbg.generated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.color
     *
     * @return the value of th_shop_order.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.color
     *
     * @param color the value for th_shop_order.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.comTime
     *
     * @return the value of th_shop_order.comTime
     *
     * @mbg.generated
     */
    public Date getComtime() {
        return comtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.comTime
     *
     * @param comtime the value for th_shop_order.comTime
     *
     * @mbg.generated
     */
    public void setComtime(Date comtime) {
        this.comtime = comtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.count
     *
     * @return the value of th_shop_order.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.count
     *
     * @param count the value for th_shop_order.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.createTime
     *
     * @return the value of th_shop_order.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.createTime
     *
     * @param createtime the value for th_shop_order.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.deleted
     *
     * @return the value of th_shop_order.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.deleted
     *
     * @param deleted the value for th_shop_order.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.money
     *
     * @return the value of th_shop_order.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.money
     *
     * @param money the value for th_shop_order.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.moneyCode
     *
     * @return the value of th_shop_order.moneyCode
     *
     * @mbg.generated
     */
    public String getMoneycode() {
        return moneycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.moneyCode
     *
     * @param moneycode the value for th_shop_order.moneyCode
     *
     * @mbg.generated
     */
    public void setMoneycode(String moneycode) {
        this.moneycode = moneycode == null ? null : moneycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.orderNo
     *
     * @return the value of th_shop_order.orderNo
     *
     * @mbg.generated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.orderNo
     *
     * @param orderno the value for th_shop_order.orderNo
     *
     * @mbg.generated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.orderType
     *
     * @return the value of th_shop_order.orderType
     *
     * @mbg.generated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.orderType
     *
     * @param ordertype the value for th_shop_order.orderType
     *
     * @mbg.generated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.password
     *
     * @return the value of th_shop_order.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.password
     *
     * @param password the value for th_shop_order.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.payTime
     *
     * @return the value of th_shop_order.payTime
     *
     * @mbg.generated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.payTime
     *
     * @param paytime the value for th_shop_order.payTime
     *
     * @mbg.generated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.payType
     *
     * @return the value of th_shop_order.payType
     *
     * @mbg.generated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.payType
     *
     * @param paytype the value for th_shop_order.payType
     *
     * @mbg.generated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.postage
     *
     * @return the value of th_shop_order.postage
     *
     * @mbg.generated
     */
    public Double getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.postage
     *
     * @param postage the value for th_shop_order.postage
     *
     * @mbg.generated
     */
    public void setPostage(Double postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.price
     *
     * @return the value of th_shop_order.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.price
     *
     * @param price the value for th_shop_order.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.sendTime
     *
     * @return the value of th_shop_order.sendTime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.sendTime
     *
     * @param sendtime the value for th_shop_order.sendTime
     *
     * @mbg.generated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.shopId
     *
     * @return the value of th_shop_order.shopId
     *
     * @mbg.generated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.shopId
     *
     * @param shopid the value for th_shop_order.shopId
     *
     * @mbg.generated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.state
     *
     * @return the value of th_shop_order.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.state
     *
     * @param state the value for th_shop_order.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.userName
     *
     * @return the value of th_shop_order.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.userName
     *
     * @param username the value for th_shop_order.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.addressId
     *
     * @return the value of th_shop_order.addressId
     *
     * @mbg.generated
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.addressId
     *
     * @param addressid the value for th_shop_order.addressId
     *
     * @mbg.generated
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.userId
     *
     * @return the value of th_shop_order.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.userId
     *
     * @param userid the value for th_shop_order.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.remark
     *
     * @return the value of th_shop_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.remark
     *
     * @param remark the value for th_shop_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.receipt
     *
     * @return the value of th_shop_order.receipt
     *
     * @mbg.generated
     */
    public String getReceipt() {
        return receipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.receipt
     *
     * @param receipt the value for th_shop_order.receipt
     *
     * @mbg.generated
     */
    public void setReceipt(String receipt) {
        this.receipt = receipt == null ? null : receipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.expressNo
     *
     * @return the value of th_shop_order.expressNo
     *
     * @mbg.generated
     */
    public String getExpressno() {
        return expressno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.expressNo
     *
     * @param expressno the value for th_shop_order.expressNo
     *
     * @mbg.generated
     */
    public void setExpressno(String expressno) {
        this.expressno = expressno == null ? null : expressno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.sendPeo
     *
     * @return the value of th_shop_order.sendPeo
     *
     * @mbg.generated
     */
    public String getSendpeo() {
        return sendpeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.sendPeo
     *
     * @param sendpeo the value for th_shop_order.sendPeo
     *
     * @mbg.generated
     */
    public void setSendpeo(String sendpeo) {
        this.sendpeo = sendpeo == null ? null : sendpeo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.expressCom
     *
     * @return the value of th_shop_order.expressCom
     *
     * @mbg.generated
     */
    public String getExpresscom() {
        return expresscom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.expressCom
     *
     * @param expresscom the value for th_shop_order.expressCom
     *
     * @mbg.generated
     */
    public void setExpresscom(String expresscom) {
        this.expresscom = expresscom == null ? null : expresscom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.sendRemark
     *
     * @return the value of th_shop_order.sendRemark
     *
     * @mbg.generated
     */
    public String getSendremark() {
        return sendremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.sendRemark
     *
     * @param sendremark the value for th_shop_order.sendRemark
     *
     * @mbg.generated
     */
    public void setSendremark(String sendremark) {
        this.sendremark = sendremark == null ? null : sendremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_order.busId
     *
     * @return the value of th_shop_order.busId
     *
     * @mbg.generated
     */
    public Integer getBusid() {
        return busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_order.busId
     *
     * @param busid the value for th_shop_order.busId
     *
     * @mbg.generated
     */
    public void setBusid(Integer busid) {
        this.busid = busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", buyaddress=").append(buyaddress);
        sb.append(", buycity=").append(buycity);
        sb.append(", buyname=").append(buyname);
        sb.append(", buyphone=").append(buyphone);
        sb.append(", buyprovince=").append(buyprovince);
        sb.append(", cardid=").append(cardid);
        sb.append(", cardno=").append(cardno);
        sb.append(", color=").append(color);
        sb.append(", comtime=").append(comtime);
        sb.append(", count=").append(count);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", money=").append(money);
        sb.append(", moneycode=").append(moneycode);
        sb.append(", orderno=").append(orderno);
        sb.append(", ordertype=").append(ordertype);
        sb.append(", password=").append(password);
        sb.append(", paytime=").append(paytime);
        sb.append(", paytype=").append(paytype);
        sb.append(", postage=").append(postage);
        sb.append(", price=").append(price);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", shopid=").append(shopid);
        sb.append(", state=").append(state);
        sb.append(", username=").append(username);
        sb.append(", addressid=").append(addressid);
        sb.append(", userid=").append(userid);
        sb.append(", remark=").append(remark);
        sb.append(", receipt=").append(receipt);
        sb.append(", expressno=").append(expressno);
        sb.append(", sendpeo=").append(sendpeo);
        sb.append(", expresscom=").append(expresscom);
        sb.append(", sendremark=").append(sendremark);
        sb.append(", busid=").append(busid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}