package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThShop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.busRemark
     *
     * @mbg.generated
     */
    private String busremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.introduce
     *
     * @mbg.generated
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.oldPrice
     *
     * @mbg.generated
     */
    private Double oldprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.orderType
     *
     * @mbg.generated
     */
    private Integer ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.parentId
     *
     * @mbg.generated
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.resCount
     *
     * @mbg.generated
     */
    private Integer rescount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.totalCount
     *
     * @mbg.generated
     */
    private Integer totalcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.htmlUrl
     *
     * @mbg.generated
     */
    private String htmlurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.readCount
     *
     * @mbg.generated
     */
    private Integer readcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.topFlag
     *
     * @mbg.generated
     */
    private Integer topflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.busId
     *
     * @mbg.generated
     */
    private Integer busid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.memberType
     *
     * @mbg.generated
     */
    private Integer membertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.id
     *
     * @return the value of th_shop.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.id
     *
     * @param id the value for th_shop.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.address
     *
     * @return the value of th_shop.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.address
     *
     * @param address the value for th_shop.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.busRemark
     *
     * @return the value of th_shop.busRemark
     *
     * @mbg.generated
     */
    public String getBusremark() {
        return busremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.busRemark
     *
     * @param busremark the value for th_shop.busRemark
     *
     * @mbg.generated
     */
    public void setBusremark(String busremark) {
        this.busremark = busremark == null ? null : busremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.color
     *
     * @return the value of th_shop.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.color
     *
     * @param color the value for th_shop.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.createTime
     *
     * @return the value of th_shop.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.createTime
     *
     * @param createtime the value for th_shop.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.deleted
     *
     * @return the value of th_shop.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.deleted
     *
     * @param deleted the value for th_shop.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.introduce
     *
     * @return the value of th_shop.introduce
     *
     * @mbg.generated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.introduce
     *
     * @param introduce the value for th_shop.introduce
     *
     * @mbg.generated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.logo
     *
     * @return the value of th_shop.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.logo
     *
     * @param logo the value for th_shop.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.name
     *
     * @return the value of th_shop.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.name
     *
     * @param name the value for th_shop.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.oldPrice
     *
     * @return the value of th_shop.oldPrice
     *
     * @mbg.generated
     */
    public Double getOldprice() {
        return oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.oldPrice
     *
     * @param oldprice the value for th_shop.oldPrice
     *
     * @mbg.generated
     */
    public void setOldprice(Double oldprice) {
        this.oldprice = oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.orderType
     *
     * @return the value of th_shop.orderType
     *
     * @mbg.generated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.orderType
     *
     * @param ordertype the value for th_shop.orderType
     *
     * @mbg.generated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.parentId
     *
     * @return the value of th_shop.parentId
     *
     * @mbg.generated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.parentId
     *
     * @param parentid the value for th_shop.parentId
     *
     * @mbg.generated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.price
     *
     * @return the value of th_shop.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.price
     *
     * @param price the value for th_shop.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.resCount
     *
     * @return the value of th_shop.resCount
     *
     * @mbg.generated
     */
    public Integer getRescount() {
        return rescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.resCount
     *
     * @param rescount the value for th_shop.resCount
     *
     * @mbg.generated
     */
    public void setRescount(Integer rescount) {
        this.rescount = rescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.totalCount
     *
     * @return the value of th_shop.totalCount
     *
     * @mbg.generated
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.totalCount
     *
     * @param totalcount the value for th_shop.totalCount
     *
     * @mbg.generated
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.type
     *
     * @return the value of th_shop.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.type
     *
     * @param type the value for th_shop.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.htmlUrl
     *
     * @return the value of th_shop.htmlUrl
     *
     * @mbg.generated
     */
    public String getHtmlurl() {
        return htmlurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.htmlUrl
     *
     * @param htmlurl the value for th_shop.htmlUrl
     *
     * @mbg.generated
     */
    public void setHtmlurl(String htmlurl) {
        this.htmlurl = htmlurl == null ? null : htmlurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.readCount
     *
     * @return the value of th_shop.readCount
     *
     * @mbg.generated
     */
    public Integer getReadcount() {
        return readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.readCount
     *
     * @param readcount the value for th_shop.readCount
     *
     * @mbg.generated
     */
    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.topFlag
     *
     * @return the value of th_shop.topFlag
     *
     * @mbg.generated
     */
    public Integer getTopflag() {
        return topflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.topFlag
     *
     * @param topflag the value for th_shop.topFlag
     *
     * @mbg.generated
     */
    public void setTopflag(Integer topflag) {
        this.topflag = topflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.busId
     *
     * @return the value of th_shop.busId
     *
     * @mbg.generated
     */
    public Integer getBusid() {
        return busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.busId
     *
     * @param busid the value for th_shop.busId
     *
     * @mbg.generated
     */
    public void setBusid(Integer busid) {
        this.busid = busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.memberType
     *
     * @return the value of th_shop.memberType
     *
     * @mbg.generated
     */
    public Integer getMembertype() {
        return membertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.memberType
     *
     * @param membertype the value for th_shop.memberType
     *
     * @mbg.generated
     */
    public void setMembertype(Integer membertype) {
        this.membertype = membertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop.content
     *
     * @return the value of th_shop.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop.content
     *
     * @param content the value for th_shop.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", busremark=").append(busremark);
        sb.append(", color=").append(color);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", introduce=").append(introduce);
        sb.append(", logo=").append(logo);
        sb.append(", name=").append(name);
        sb.append(", oldprice=").append(oldprice);
        sb.append(", ordertype=").append(ordertype);
        sb.append(", parentid=").append(parentid);
        sb.append(", price=").append(price);
        sb.append(", rescount=").append(rescount);
        sb.append(", totalcount=").append(totalcount);
        sb.append(", type=").append(type);
        sb.append(", htmlurl=").append(htmlurl);
        sb.append(", readcount=").append(readcount);
        sb.append(", topflag=").append(topflag);
        sb.append(", busid=").append(busid);
        sb.append(", membertype=").append(membertype);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}