package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThShopCode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.cardCompany
     *
     * @mbg.generated
     */
    private String cardcompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.orderNo
     *
     * @mbg.generated
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.shopId
     *
     * @mbg.generated
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.startTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_shop_code.useTime
     *
     * @mbg.generated
     */
    private Date usetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.id
     *
     * @return the value of th_shop_code.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.id
     *
     * @param id the value for th_shop_code.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.cardCompany
     *
     * @return the value of th_shop_code.cardCompany
     *
     * @mbg.generated
     */
    public String getCardcompany() {
        return cardcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.cardCompany
     *
     * @param cardcompany the value for th_shop_code.cardCompany
     *
     * @mbg.generated
     */
    public void setCardcompany(String cardcompany) {
        this.cardcompany = cardcompany == null ? null : cardcompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.code
     *
     * @return the value of th_shop_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.code
     *
     * @param code the value for th_shop_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.createTime
     *
     * @return the value of th_shop_code.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.createTime
     *
     * @param createtime the value for th_shop_code.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.deleted
     *
     * @return the value of th_shop_code.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.deleted
     *
     * @param deleted the value for th_shop_code.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.endTime
     *
     * @return the value of th_shop_code.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.endTime
     *
     * @param endtime the value for th_shop_code.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.money
     *
     * @return the value of th_shop_code.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.money
     *
     * @param money the value for th_shop_code.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.orderNo
     *
     * @return the value of th_shop_code.orderNo
     *
     * @mbg.generated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.orderNo
     *
     * @param orderno the value for th_shop_code.orderNo
     *
     * @mbg.generated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.shopId
     *
     * @return the value of th_shop_code.shopId
     *
     * @mbg.generated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.shopId
     *
     * @param shopid the value for th_shop_code.shopId
     *
     * @mbg.generated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.startTime
     *
     * @return the value of th_shop_code.startTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.startTime
     *
     * @param starttime the value for th_shop_code.startTime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.state
     *
     * @return the value of th_shop_code.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.state
     *
     * @param state the value for th_shop_code.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_shop_code.useTime
     *
     * @return the value of th_shop_code.useTime
     *
     * @mbg.generated
     */
    public Date getUsetime() {
        return usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_shop_code.useTime
     *
     * @param usetime the value for th_shop_code.useTime
     *
     * @mbg.generated
     */
    public void setUsetime(Date usetime) {
        this.usetime = usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cardcompany=").append(cardcompany);
        sb.append(", code=").append(code);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", endtime=").append(endtime);
        sb.append(", money=").append(money);
        sb.append(", orderno=").append(orderno);
        sb.append(", shopid=").append(shopid);
        sb.append(", starttime=").append(starttime);
        sb.append(", state=").append(state);
        sb.append(", usetime=").append(usetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}