package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ThSuggest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_suggest.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_suggest.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_suggest.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_suggest.facNo
     *
     * @mbg.generated
     */
    private String facno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_suggest.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column th_suggest.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table th_suggest
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_suggest.id
     *
     * @return the value of th_suggest.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_suggest.id
     *
     * @param id the value for th_suggest.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_suggest.content
     *
     * @return the value of th_suggest.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_suggest.content
     *
     * @param content the value for th_suggest.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_suggest.createTime
     *
     * @return the value of th_suggest.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_suggest.createTime
     *
     * @param createtime the value for th_suggest.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_suggest.facNo
     *
     * @return the value of th_suggest.facNo
     *
     * @mbg.generated
     */
    public String getFacno() {
        return facno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_suggest.facNo
     *
     * @param facno the value for th_suggest.facNo
     *
     * @mbg.generated
     */
    public void setFacno(String facno) {
        this.facno = facno == null ? null : facno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_suggest.deleted
     *
     * @return the value of th_suggest.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_suggest.deleted
     *
     * @param deleted the value for th_suggest.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column th_suggest.state
     *
     * @return the value of th_suggest.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column th_suggest.state
     *
     * @param state the value for th_suggest.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_suggest
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", createtime=").append(createtime);
        sb.append(", facno=").append(facno);
        sb.append(", deleted=").append(deleted);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}