package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class UserSysEnumeration implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.createby
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.displayno
     *
     * @mbg.generated
     */
    private Integer displayno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.parentid
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.thecode
     *
     * @mbg.generated
     */
    private String thecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.thekey
     *
     * @mbg.generated
     */
    private Integer thekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.thevalue
     *
     * @mbg.generated
     */
    private String thevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.organId
     *
     * @mbg.generated
     */
    private Integer organid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_enumeration.mapping
     *
     * @mbg.generated
     */
    private String mapping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.id
     *
     * @return the value of user_sys_enumeration.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.id
     *
     * @param id the value for user_sys_enumeration.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.createby
     *
     * @return the value of user_sys_enumeration.createby
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.createby
     *
     * @param createby the value for user_sys_enumeration.createby
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.createtime
     *
     * @return the value of user_sys_enumeration.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.createtime
     *
     * @param createtime the value for user_sys_enumeration.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.deleted
     *
     * @return the value of user_sys_enumeration.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.deleted
     *
     * @param deleted the value for user_sys_enumeration.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.description
     *
     * @return the value of user_sys_enumeration.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.description
     *
     * @param description the value for user_sys_enumeration.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.displayno
     *
     * @return the value of user_sys_enumeration.displayno
     *
     * @mbg.generated
     */
    public Integer getDisplayno() {
        return displayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.displayno
     *
     * @param displayno the value for user_sys_enumeration.displayno
     *
     * @mbg.generated
     */
    public void setDisplayno(Integer displayno) {
        this.displayno = displayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.name
     *
     * @return the value of user_sys_enumeration.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.name
     *
     * @param name the value for user_sys_enumeration.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.parentid
     *
     * @return the value of user_sys_enumeration.parentid
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.parentid
     *
     * @param parentid the value for user_sys_enumeration.parentid
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.thecode
     *
     * @return the value of user_sys_enumeration.thecode
     *
     * @mbg.generated
     */
    public String getThecode() {
        return thecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.thecode
     *
     * @param thecode the value for user_sys_enumeration.thecode
     *
     * @mbg.generated
     */
    public void setThecode(String thecode) {
        this.thecode = thecode == null ? null : thecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.thekey
     *
     * @return the value of user_sys_enumeration.thekey
     *
     * @mbg.generated
     */
    public Integer getThekey() {
        return thekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.thekey
     *
     * @param thekey the value for user_sys_enumeration.thekey
     *
     * @mbg.generated
     */
    public void setThekey(Integer thekey) {
        this.thekey = thekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.thevalue
     *
     * @return the value of user_sys_enumeration.thevalue
     *
     * @mbg.generated
     */
    public String getThevalue() {
        return thevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.thevalue
     *
     * @param thevalue the value for user_sys_enumeration.thevalue
     *
     * @mbg.generated
     */
    public void setThevalue(String thevalue) {
        this.thevalue = thevalue == null ? null : thevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.organId
     *
     * @return the value of user_sys_enumeration.organId
     *
     * @mbg.generated
     */
    public Integer getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.organId
     *
     * @param organid the value for user_sys_enumeration.organId
     *
     * @mbg.generated
     */
    public void setOrganid(Integer organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_enumeration.mapping
     *
     * @return the value of user_sys_enumeration.mapping
     *
     * @mbg.generated
     */
    public String getMapping() {
        return mapping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_enumeration.mapping
     *
     * @param mapping the value for user_sys_enumeration.mapping
     *
     * @mbg.generated
     */
    public void setMapping(String mapping) {
        this.mapping = mapping == null ? null : mapping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createby=").append(createby);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", description=").append(description);
        sb.append(", displayno=").append(displayno);
        sb.append(", name=").append(name);
        sb.append(", parentid=").append(parentid);
        sb.append(", thecode=").append(thecode);
        sb.append(", thekey=").append(thekey);
        sb.append(", thevalue=").append(thevalue);
        sb.append(", organid=").append(organid);
        sb.append(", mapping=").append(mapping);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}