package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class UserOrgan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.parentid
     *
     * @mbg.generated
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.enumFlag
     *
     * @mbg.generated
     */
    private Integer enumflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.userCount
     *
     * @mbg.generated
     */
    private Integer usercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.contactsName
     *
     * @mbg.generated
     */
    private String contactsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.contactsPhoneNo
     *
     * @mbg.generated
     */
    private String contactsphoneno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.cvDownCount
     *
     * @mbg.generated
     */
    private Integer cvdowncount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_organ.messageCount
     *
     * @mbg.generated
     */
    private Integer messagecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_organ
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.id
     *
     * @return the value of user_organ.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.id
     *
     * @param id the value for user_organ.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.code
     *
     * @return the value of user_organ.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.code
     *
     * @param code the value for user_organ.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.createTime
     *
     * @return the value of user_organ.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.createTime
     *
     * @param createtime the value for user_organ.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.deleted
     *
     * @return the value of user_organ.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.deleted
     *
     * @param deleted the value for user_organ.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.description
     *
     * @return the value of user_organ.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.description
     *
     * @param description the value for user_organ.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.name
     *
     * @return the value of user_organ.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.name
     *
     * @param name the value for user_organ.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.parentid
     *
     * @return the value of user_organ.parentid
     *
     * @mbg.generated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.parentid
     *
     * @param parentid the value for user_organ.parentid
     *
     * @mbg.generated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.enumFlag
     *
     * @return the value of user_organ.enumFlag
     *
     * @mbg.generated
     */
    public Integer getEnumflag() {
        return enumflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.enumFlag
     *
     * @param enumflag the value for user_organ.enumFlag
     *
     * @mbg.generated
     */
    public void setEnumflag(Integer enumflag) {
        this.enumflag = enumflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.endTime
     *
     * @return the value of user_organ.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.endTime
     *
     * @param endtime the value for user_organ.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.userCount
     *
     * @return the value of user_organ.userCount
     *
     * @mbg.generated
     */
    public Integer getUsercount() {
        return usercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.userCount
     *
     * @param usercount the value for user_organ.userCount
     *
     * @mbg.generated
     */
    public void setUsercount(Integer usercount) {
        this.usercount = usercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.contactsName
     *
     * @return the value of user_organ.contactsName
     *
     * @mbg.generated
     */
    public String getContactsname() {
        return contactsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.contactsName
     *
     * @param contactsname the value for user_organ.contactsName
     *
     * @mbg.generated
     */
    public void setContactsname(String contactsname) {
        this.contactsname = contactsname == null ? null : contactsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.contactsPhoneNo
     *
     * @return the value of user_organ.contactsPhoneNo
     *
     * @mbg.generated
     */
    public String getContactsphoneno() {
        return contactsphoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.contactsPhoneNo
     *
     * @param contactsphoneno the value for user_organ.contactsPhoneNo
     *
     * @mbg.generated
     */
    public void setContactsphoneno(String contactsphoneno) {
        this.contactsphoneno = contactsphoneno == null ? null : contactsphoneno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.cvDownCount
     *
     * @return the value of user_organ.cvDownCount
     *
     * @mbg.generated
     */
    public Integer getCvdowncount() {
        return cvdowncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.cvDownCount
     *
     * @param cvdowncount the value for user_organ.cvDownCount
     *
     * @mbg.generated
     */
    public void setCvdowncount(Integer cvdowncount) {
        this.cvdowncount = cvdowncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_organ.messageCount
     *
     * @return the value of user_organ.messageCount
     *
     * @mbg.generated
     */
    public Integer getMessagecount() {
        return messagecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_organ.messageCount
     *
     * @param messagecount the value for user_organ.messageCount
     *
     * @mbg.generated
     */
    public void setMessagecount(Integer messagecount) {
        this.messagecount = messagecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_organ
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", description=").append(description);
        sb.append(", name=").append(name);
        sb.append(", parentid=").append(parentid);
        sb.append(", enumflag=").append(enumflag);
        sb.append(", endtime=").append(endtime);
        sb.append(", usercount=").append(usercount);
        sb.append(", contactsname=").append(contactsname);
        sb.append(", contactsphoneno=").append(contactsphoneno);
        sb.append(", cvdowncount=").append(cvdowncount);
        sb.append(", messagecount=").append(messagecount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}