package com.golden.website.dataobject;

import java.io.Serializable;

public class UserSysArea implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.areaId
     *
     * @mbg.generated
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.areaNo
     *
     * @mbg.generated
     */
    private String areano;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.areaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.sortNo
     *
     * @mbg.generated
     */
    private Byte sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.prevArea
     *
     * @mbg.generated
     */
    private String prevarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_area.enNo
     *
     * @mbg.generated
     */
    private String enno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_sys_area
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.areaId
     *
     * @return the value of user_sys_area.areaId
     *
     * @mbg.generated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.areaId
     *
     * @param areaid the value for user_sys_area.areaId
     *
     * @mbg.generated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.areaNo
     *
     * @return the value of user_sys_area.areaNo
     *
     * @mbg.generated
     */
    public String getAreano() {
        return areano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.areaNo
     *
     * @param areano the value for user_sys_area.areaNo
     *
     * @mbg.generated
     */
    public void setAreano(String areano) {
        this.areano = areano == null ? null : areano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.areaName
     *
     * @return the value of user_sys_area.areaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.areaName
     *
     * @param areaname the value for user_sys_area.areaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.sortNo
     *
     * @return the value of user_sys_area.sortNo
     *
     * @mbg.generated
     */
    public Byte getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.sortNo
     *
     * @param sortno the value for user_sys_area.sortNo
     *
     * @mbg.generated
     */
    public void setSortno(Byte sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.prevArea
     *
     * @return the value of user_sys_area.prevArea
     *
     * @mbg.generated
     */
    public String getPrevarea() {
        return prevarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.prevArea
     *
     * @param prevarea the value for user_sys_area.prevArea
     *
     * @mbg.generated
     */
    public void setPrevarea(String prevarea) {
        this.prevarea = prevarea == null ? null : prevarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.deleted
     *
     * @return the value of user_sys_area.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.deleted
     *
     * @param deleted the value for user_sys_area.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.state
     *
     * @return the value of user_sys_area.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.state
     *
     * @param state the value for user_sys_area.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_area.enNo
     *
     * @return the value of user_sys_area.enNo
     *
     * @mbg.generated
     */
    public String getEnno() {
        return enno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_area.enNo
     *
     * @param enno the value for user_sys_area.enNo
     *
     * @mbg.generated
     */
    public void setEnno(String enno) {
        this.enno = enno == null ? null : enno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_area
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areaid=").append(areaid);
        sb.append(", areano=").append(areano);
        sb.append(", areaname=").append(areaname);
        sb.append(", sortno=").append(sortno);
        sb.append(", prevarea=").append(prevarea);
        sb.append(", deleted=").append(deleted);
        sb.append(", state=").append(state);
        sb.append(", enno=").append(enno);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}