package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class UserSysErrorLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.fromType
     *
     * @mbg.generated
     */
    private Integer fromtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.mainUserId
     *
     * @mbg.generated
     */
    private Integer mainuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.moduleName
     *
     * @mbg.generated
     */
    private String modulename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_error_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_sys_error_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.id
     *
     * @return the value of user_sys_error_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.id
     *
     * @param id the value for user_sys_error_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.createTime
     *
     * @return the value of user_sys_error_log.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.createTime
     *
     * @param createtime the value for user_sys_error_log.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.fromType
     *
     * @return the value of user_sys_error_log.fromType
     *
     * @mbg.generated
     */
    public Integer getFromtype() {
        return fromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.fromType
     *
     * @param fromtype the value for user_sys_error_log.fromType
     *
     * @mbg.generated
     */
    public void setFromtype(Integer fromtype) {
        this.fromtype = fromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.mainUserId
     *
     * @return the value of user_sys_error_log.mainUserId
     *
     * @mbg.generated
     */
    public Integer getMainuserid() {
        return mainuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.mainUserId
     *
     * @param mainuserid the value for user_sys_error_log.mainUserId
     *
     * @mbg.generated
     */
    public void setMainuserid(Integer mainuserid) {
        this.mainuserid = mainuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.moduleName
     *
     * @return the value of user_sys_error_log.moduleName
     *
     * @mbg.generated
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.moduleName
     *
     * @param modulename the value for user_sys_error_log.moduleName
     *
     * @mbg.generated
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.nickName
     *
     * @return the value of user_sys_error_log.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.nickName
     *
     * @param nickname the value for user_sys_error_log.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.userId
     *
     * @return the value of user_sys_error_log.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.userId
     *
     * @param userid the value for user_sys_error_log.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.userName
     *
     * @return the value of user_sys_error_log.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.userName
     *
     * @param username the value for user_sys_error_log.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_error_log.remark
     *
     * @return the value of user_sys_error_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_error_log.remark
     *
     * @param remark the value for user_sys_error_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_error_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createtime=").append(createtime);
        sb.append(", fromtype=").append(fromtype);
        sb.append(", mainuserid=").append(mainuserid);
        sb.append(", modulename=").append(modulename);
        sb.append(", nickname=").append(nickname);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}