package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class UserSysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.phoneno
     *
     * @mbg.generated
     */
    private String phoneno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.updatePwdTime
     *
     * @mbg.generated
     */
    private Date updatepwdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.organId
     *
     * @mbg.generated
     */
    private Integer organid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.organName
     *
     * @mbg.generated
     */
    private String organname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sys_user.organNo
     *
     * @mbg.generated
     */
    private String organno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.id
     *
     * @return the value of user_sys_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.id
     *
     * @param id the value for user_sys_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.createTime
     *
     * @return the value of user_sys_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.createTime
     *
     * @param createtime the value for user_sys_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.deleted
     *
     * @return the value of user_sys_user.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.deleted
     *
     * @param deleted the value for user_sys_user.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.duty
     *
     * @return the value of user_sys_user.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.duty
     *
     * @param duty the value for user_sys_user.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.email
     *
     * @return the value of user_sys_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.email
     *
     * @param email the value for user_sys_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.name
     *
     * @return the value of user_sys_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.name
     *
     * @param name the value for user_sys_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.nickName
     *
     * @return the value of user_sys_user.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.nickName
     *
     * @param nickname the value for user_sys_user.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.password
     *
     * @return the value of user_sys_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.password
     *
     * @param password the value for user_sys_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.phoneno
     *
     * @return the value of user_sys_user.phoneno
     *
     * @mbg.generated
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.phoneno
     *
     * @param phoneno the value for user_sys_user.phoneno
     *
     * @mbg.generated
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno == null ? null : phoneno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.sex
     *
     * @return the value of user_sys_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.sex
     *
     * @param sex the value for user_sys_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.state
     *
     * @return the value of user_sys_user.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.state
     *
     * @param state the value for user_sys_user.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.type
     *
     * @return the value of user_sys_user.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.type
     *
     * @param type the value for user_sys_user.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.updatePwdTime
     *
     * @return the value of user_sys_user.updatePwdTime
     *
     * @mbg.generated
     */
    public Date getUpdatepwdtime() {
        return updatepwdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.updatePwdTime
     *
     * @param updatepwdtime the value for user_sys_user.updatePwdTime
     *
     * @mbg.generated
     */
    public void setUpdatepwdtime(Date updatepwdtime) {
        this.updatepwdtime = updatepwdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.userName
     *
     * @return the value of user_sys_user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.userName
     *
     * @param username the value for user_sys_user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.organId
     *
     * @return the value of user_sys_user.organId
     *
     * @mbg.generated
     */
    public Integer getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.organId
     *
     * @param organid the value for user_sys_user.organId
     *
     * @mbg.generated
     */
    public void setOrganid(Integer organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.organName
     *
     * @return the value of user_sys_user.organName
     *
     * @mbg.generated
     */
    public String getOrganname() {
        return organname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.organName
     *
     * @param organname the value for user_sys_user.organName
     *
     * @mbg.generated
     */
    public void setOrganname(String organname) {
        this.organname = organname == null ? null : organname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sys_user.organNo
     *
     * @return the value of user_sys_user.organNo
     *
     * @mbg.generated
     */
    public String getOrganno() {
        return organno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sys_user.organNo
     *
     * @param organno the value for user_sys_user.organNo
     *
     * @mbg.generated
     */
    public void setOrganno(String organno) {
        this.organno = organno == null ? null : organno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createtime=").append(createtime);
        sb.append(", deleted=").append(deleted);
        sb.append(", duty=").append(duty);
        sb.append(", email=").append(email);
        sb.append(", name=").append(name);
        sb.append(", nickname=").append(nickname);
        sb.append(", password=").append(password);
        sb.append(", phoneno=").append(phoneno);
        sb.append(", sex=").append(sex);
        sb.append(", state=").append(state);
        sb.append(", type=").append(type);
        sb.append(", updatepwdtime=").append(updatepwdtime);
        sb.append(", username=").append(username);
        sb.append(", organid=").append(organid);
        sb.append(", organname=").append(organname);
        sb.append(", organno=").append(organno);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}