package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class WebsiteUploadDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.file_id
     *
     * @mbg.generated
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.update
     *
     * @mbg.generated
     */
    private Date fileupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.filepath
     *
     * @mbg.generated
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.fileuploader
     *
     * @mbg.generated
     */
    private String fileuploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.isdelete
     *
     * @mbg.generated
     */
    private String isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.desc
     *
     * @mbg.generated
     */
    private String filedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_upload_detail.filetype
     *
     * @mbg.generated
     */
    private String filetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_upload_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.fileid
     *
     * @return the value of website_upload_detail.file_id
     * @mbg.generated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.fileid
     *
     * @param fileid the value for website_upload_detail.file_id
     * @mbg.generated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.filename
     *
     * @return the value of website_upload_detail.filename
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.filename
     *
     * @param filename the value for website_upload_detail.filename
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.fileupdate
     *
     * @return the value of website_upload_detail.fileupdate
     * @mbg.generated
     */
    public Date getFileupdate() {
        return fileupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.fileupdate
     *
     * @param fileupdate the value for website_upload_detail.fileupdate
     * @mbg.generated
     */

    public void setFileupdate(Date fileupdate) {
        this.fileupdate = fileupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.filepath
     *
     * @return the value of website_upload_detail.filepath
     * @mbg.generated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.filepath
     *
     * @param filepath the value for website_upload_detail.filepath
     * @mbg.generated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.fileuploader
     *
     * @return the value of website_upload_detail.fileuploader
     * @mbg.generated
     */
    public String getFileuploader() {
        return fileuploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.fileuploader
     *
     * @param fileuploader the value for website_upload_detail.uploader
     * @mbg.generated
     */
    public void setFileuploader(String fileuploader) {
        this.fileuploader = fileuploader == null ? null : fileuploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.isdelete
     *
     * @return the value of website_upload_detail.isdelete
     * @mbg.generated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.isdelete
     *
     * @param isdelete the value for website_upload_detail.isdelete
     * @mbg.generated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.filedesc
     *
     * @return the value of website_upload_detail.filedesc
     * @mbg.generated
     */
    public String getFiledesc() {
        return filedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.filedesc
     *
     * @param filedesc the value for website_upload_detail.filedesc
     * @mbg.generated
     */
    public void setFiledesc(String filedesc) {
        this.filedesc = filedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_upload_detail.filetype
     *
     * @return the value of website_upload_detail.filetype
     * @mbg.generated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_upload_detail.filetype
     *
     * @param filetype the value for website_upload_detail.filetype
     * @mbg.generated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_upload_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(" {");
        sb.append(" \"fileid\":\"").append(fileid);
        sb.append(", \"filename\":\"").append(filename);
        sb.append(", \"fileupdate\":\"").append(fileupdate);
        sb.append(", \"filepath\":\"").append(filepath);
        sb.append(", \"fileuploader\":\"").append(fileuploader);
        sb.append(", \"isdelete\":\"").append(isdelete);
        sb.append(", \"filedesc\":\"").append(filedesc);
        sb.append(", \"filetype\":\"").append(filetype);
        sb.append("\"}");
        return sb.toString();
    }
}