package com.golden.website.dataobject;

import java.io.Serializable;
import java.util.Date;

public class WebsiteHomeproduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.imgUrl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.hrefUrl
     *
     * @mbg.generated
     */
    private String hrefurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.order
     *
     * @mbg.generated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_homeproduct.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.id
     *
     * @return the value of website_homeproduct.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.id
     *
     * @param id the value for website_homeproduct.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.title
     *
     * @return the value of website_homeproduct.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.title
     *
     * @param title the value for website_homeproduct.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.imgUrl
     *
     * @return the value of website_homeproduct.imgUrl
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.imgUrl
     *
     * @param imgurl the value for website_homeproduct.imgUrl
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.hrefUrl
     *
     * @return the value of website_homeproduct.hrefUrl
     * @mbg.generated
     */
    public String getHrefurl() {
        return hrefurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.hrefUrl
     *
     * @param hrefurl the value for website_homeproduct.hrefUrl
     * @mbg.generated
     */
    public void setHrefurl(String hrefurl) {
        this.hrefurl = hrefurl == null ? null : hrefurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.content
     *
     * @return the value of website_homeproduct.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.content
     *
     * @param content the value for website_homeproduct.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.order
     *
     * @return the value of website_homeproduct.order
     * @mbg.generated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.order
     *
     * @param order the value for website_homeproduct.order
     * @mbg.generated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_homeproduct.createtime
     *
     * @return the value of website_homeproduct.createtime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_homeproduct.createtime
     *
     * @param createtime the value for website_homeproduct.createtime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        sb.append("\"id\":\"").append(id);
        sb.append("\", \"title\":\"").append(title);
        sb.append("\", \"imgurl\":\"").append(imgurl);
        sb.append("\", \"hrefurl\":\"").append(hrefurl);
        sb.append("\", \"content\":\"").append(content);
        sb.append("\", \"order\":\"").append(order);
        sb.append("\", \"createtime\":\"").append(createtime);
        sb.append("\"}");
        return sb.toString();
    }
}