package com.golden.website.dao;

import com.golden.website.dataobject.GcSysinfo;
import java.util.List;

public interface GcSysinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_sysinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String infoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_sysinfo
     *
     * @mbg.generated
     */
    int insert(GcSysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_sysinfo
     *
     * @mbg.generated
     */
    GcSysinfo selectByPrimaryKey(String infoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_sysinfo
     *
     * @mbg.generated
     */
    List<GcSysinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gc_sysinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GcSysinfo record);
}