package com.golden.website.dao;

import com.golden.website.dataobject.GdAbout;
import java.util.List;

public interface GdAboutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_about
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_about
     *
     * @mbg.generated
     */
    int insert(GdAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_about
     *
     * @mbg.generated
     */
    GdAbout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_about
     *
     * @mbg.generated
     */
    List<GdAbout> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_about
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GdAbout record);
}