package com.golden.website.dao;

import com.golden.website.dataobject.GdAnli;
import java.util.List;

public interface GdAnliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_anli
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_anli
     *
     * @mbg.generated
     */
    int insert(GdAnli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_anli
     *
     * @mbg.generated
     */
    GdAnli selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_anli
     *
     * @mbg.generated
     */
    List<GdAnli> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_anli
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GdAnli record);
}