package com.golden.website.dao;

import com.golden.website.dataobject.GdDatamanage;
import java.util.List;

public interface GdDatamanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_datamanage
     *
     * @mbg.generated
     */
    int insert(GdDatamanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_datamanage
     *
     * @mbg.generated
     */
    List<GdDatamanage> selectAll();
}