package com.golden.website.dao;

import com.golden.website.dataobject.GdOrder;
import java.util.List;

public interface GdOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_order
     *
     * @mbg.generated
     */
    int insert(GdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_order
     *
     * @mbg.generated
     */
    GdOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_order
     *
     * @mbg.generated
     */
    List<GdOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GdOrder record);
}