package com.golden.website.dao;

import com.golden.website.dataobject.GdProduct;
import java.util.List;

public interface GdProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_product
     *
     * @mbg.generated
     */
    int insert(GdProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_product
     *
     * @mbg.generated
     */
    GdProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_product
     *
     * @mbg.generated
     */
    List<GdProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GdProduct record);
}