package com.golden.website.dao;

import com.golden.website.dataobject.GoldenMeeting;
import java.util.List;

public interface GoldenMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_meeting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_meeting
     *
     * @mbg.generated
     */
    int insert(GoldenMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_meeting
     *
     * @mbg.generated
     */
    GoldenMeeting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_meeting
     *
     * @mbg.generated
     */
    List<GoldenMeeting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoldenMeeting record);
}