package com.golden.website.dao;

import com.golden.website.dataobject.GoldenProjectCheck;
import java.util.List;

public interface GoldenProjectCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_check
     *
     * @mbg.generated
     */
    int insert(GoldenProjectCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_check
     *
     * @mbg.generated
     */
    GoldenProjectCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_check
     *
     * @mbg.generated
     */
    List<GoldenProjectCheck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoldenProjectCheck record);
}