package com.golden.website.dao;

import com.golden.website.dataobject.GoldenProjectSqDown;
import java.util.List;

public interface GoldenProjectSqDownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_sq_down
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_sq_down
     *
     * @mbg.generated
     */
    int insert(GoldenProjectSqDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_sq_down
     *
     * @mbg.generated
     */
    GoldenProjectSqDown selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_sq_down
     *
     * @mbg.generated
     */
    List<GoldenProjectSqDown> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_project_sq_down
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoldenProjectSqDown record);
}