package com.golden.website.dao;

import com.golden.website.dataobject.Logs;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Update;

import java.util.List;
@Mapper
public interface LogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbg.generated
     */
    @Insert("INSERT INTO LOGS (ID,URL,METHOD,IP,CLASS_METHOD,ARGS,RESPONSE,REQTIME,TIMECOST) " +
            "VALUES " +
            "(#{id},#{url},#{method},#{ip},#{classMethod},#{args},#{response},#{reqtime},#{timecost})")
    int insert(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbg.generated
     */
    Logs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbg.generated
     */
    List<Logs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs
     *
     * @mbg.generated
     */
    @Update("UPDATE LOGS SET RESPONSE=#{response}, TIMECOST=#{timecost} WHERE ID = #{id}")
    int updateByPrimaryKey(Logs record);
}