package com.golden.website.dao;

import com.golden.website.dataobject.MzActionlog;
import java.util.List;

public interface MzActionlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_actionlog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_actionlog
     *
     * @mbg.generated
     */
    int insert(MzActionlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_actionlog
     *
     * @mbg.generated
     */
    MzActionlog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_actionlog
     *
     * @mbg.generated
     */
    List<MzActionlog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_actionlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MzActionlog record);
}