package com.golden.website.dao;

import com.golden.website.dataobject.MzUser;
import java.util.List;

public interface MzUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_user
     *
     * @mbg.generated
     */
    int insert(MzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_user
     *
     * @mbg.generated
     */
    MzUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_user
     *
     * @mbg.generated
     */
    List<MzUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MzUser record);
}