package com.golden.website.dao;

import com.golden.website.dataobject.ThAppFund;
import java.util.List;

public interface ThAppFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_fund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_fund
     *
     * @mbg.generated
     */
    int insert(ThAppFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_fund
     *
     * @mbg.generated
     */
    ThAppFund selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_fund
     *
     * @mbg.generated
     */
    List<ThAppFund> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_fund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThAppFund record);
}