package com.golden.website.dao;

import com.golden.website.dataobject.ThAppMsgcode;
import java.util.List;

public interface ThAppMsgcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    int insert(ThAppMsgcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    ThAppMsgcode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    List<ThAppMsgcode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_app_msgcode
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThAppMsgcode record);
}