package com.golden.website.dao;

import com.golden.website.dataobject.ThNoticeGood;
import java.util.List;

public interface ThNoticeGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_notice_good
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_notice_good
     *
     * @mbg.generated
     */
    int insert(ThNoticeGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_notice_good
     *
     * @mbg.generated
     */
    ThNoticeGood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_notice_good
     *
     * @mbg.generated
     */
    List<ThNoticeGood> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_notice_good
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThNoticeGood record);
}