package com.golden.website.dao;

import com.golden.website.dataobject.ThRegister;
import java.util.List;

public interface ThRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_register
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_register
     *
     * @mbg.generated
     */
    int insert(ThRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_register
     *
     * @mbg.generated
     */
    ThRegister selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_register
     *
     * @mbg.generated
     */
    List<ThRegister> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_register
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThRegister record);
}