package com.golden.website.dao;

import com.golden.website.dataobject.ThShop;
import java.util.List;

public interface ThShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    int insert(ThShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    ThShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    List<ThShop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThShop record);
}