package com.golden.website.dao;

import com.golden.website.dataobject.ThShopPic;
import java.util.List;

public interface ThShopPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_pic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_pic
     *
     * @mbg.generated
     */
    int insert(ThShopPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_pic
     *
     * @mbg.generated
     */
    ThShopPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_pic
     *
     * @mbg.generated
     */
    List<ThShopPic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThShopPic record);
}