package com.golden.website.dao;

import com.golden.website.dataobject.ThShopCode;
import java.util.List;

public interface ThShopCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    int insert(ThShopCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    ThShopCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    List<ThShopCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_shop_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThShopCode record);
}