package com.golden.website.dao;

import com.golden.website.dataobject.ThUser;
import java.util.List;

public interface ThUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_user
     *
     * @mbg.generated
     */
    int insert(ThUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_user
     *
     * @mbg.generated
     */
    ThUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_user
     *
     * @mbg.generated
     */
    List<ThUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table th_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThUser record);
}