package com.golden.website.dao;

import com.golden.website.dataobject.UserPosition;
import java.util.List;

public interface UserPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_position
     *
     * @mbg.generated
     */
    int insert(UserPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_position
     *
     * @mbg.generated
     */
    UserPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_position
     *
     * @mbg.generated
     */
    List<UserPosition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPosition record);
}