package com.golden.website.dao;

import com.golden.website.dataobject.UserSysFunction;
import java.util.List;

public interface UserSysFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_function
     *
     * @mbg.generated
     */
    int insert(UserSysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_function
     *
     * @mbg.generated
     */
    UserSysFunction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_function
     *
     * @mbg.generated
     */
    List<UserSysFunction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserSysFunction record);
}