package com.golden.website.dao;

import com.golden.website.dataobject.UserRecharge;
import java.util.List;

public interface UserRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge
     *
     * @mbg.generated
     */
    int insert(UserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge
     *
     * @mbg.generated
     */
    UserRecharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge
     *
     * @mbg.generated
     */
    List<UserRecharge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRecharge record);
}