package com.golden.website.dao;

import com.golden.website.dataobject.UserSysRolefunction;
import java.util.List;

public interface UserSysRolefunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_rolefunction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_rolefunction
     *
     * @mbg.generated
     */
    int insert(UserSysRolefunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_rolefunction
     *
     * @mbg.generated
     */
    UserSysRolefunction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_rolefunction
     *
     * @mbg.generated
     */
    List<UserSysRolefunction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_rolefunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserSysRolefunction record);
}