package com.golden.website.dao;

import com.golden.website.dataobject.UserSysEnumeration;
import java.util.List;

public interface UserSysEnumerationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    int insert(UserSysEnumeration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    UserSysEnumeration selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    List<UserSysEnumeration> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_enumeration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserSysEnumeration record);
}