package com.golden.website.dao;

import com.golden.website.dataobject.WebsiteIndustrycase;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface WebsiteIndustrycaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_industrycase
     *
     * @mbg.generated
     */
    @Delete("delete from website_industrycase where id = #{id}")
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_industrycase
     *
     * @mbg.generated
     */
    @Insert("insert into website_industrycase (id,title,imgurl,hrefurl,`order`,createtime) values(#{id},#{title},#{imgurl},#{hrefurl},#{order},#{createtime}) ")
    int insert(WebsiteIndustrycase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_industrycase
     *
     * @mbg.generated
     */
    @Select("select * from website_industrycase where id =#{id}")
    WebsiteIndustrycase selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_industrycase
     *
     * @mbg.generated
     */
    @Select("select * from website_industrycase order by `order` asc")
    List<WebsiteIndustrycase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_industrycase
     *
     * @mbg.generated
     */
    @Update("update website_industrycase set title = #{title},imgurl = #{imgurl},hrefurl=#{hrefurl},`order`=#{order},createtime=#{createtime} where id = #{id}")
    int updateByPrimaryKey(WebsiteIndustrycase record);

    @Update("update website_industrycase set title = #{title},hrefurl=#{hrefurl},`order`=#{order},createtime=#{createtime} where id = #{id}")
    int updateByPrimaryKeyNotUrl(WebsiteIndustrycase record);
}