package com.golden.website.dao;

import com.golden.website.dataobject.WebsiteHomeproduct;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface WebsiteHomeproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    @Delete("delete from website_homeproduct where id = #{id}")
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    @Insert("insert into website_homeproduct (id,title,imgurl,hrefurl,content,`order`,createtime) values (#{id},#{title},#{imgurl},#{hrefurl},#{content},#{order},#{createtime})")
    int insert(WebsiteHomeproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    @Select("select * from website_homeproduct where id = #{id}")
    WebsiteHomeproduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    @Select("select * from website_homeproduct order by `order` asc")
    List<WebsiteHomeproduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_homeproduct
     *
     * @mbg.generated
     */
    @Update("update website_homeproduct set title = #{title},imgurl = #{imgurl},hrefurl = #{hrefurl},content = #{content},`order`=#{order} where id= #{id}")
    int updateByPrimaryKey(WebsiteHomeproduct record);

    @Update("update website_homeproduct set title = #{title},hrefurl = #{hrefurl},content = #{content},`order`=#{order} where id= #{id}")
    int updateByPrimaryKeyNotUrl(WebsiteHomeproduct record);
    @Select("select * from website_homeproduct order by `order` asc limit 0,1")
    WebsiteHomeproduct getHomeProductTop_1();

    @Select("select * from website_homeproduct order by `order` asc limit 1,1")
    WebsiteHomeproduct getHomeProductTop_2();
}