package com.golden.website.dao;

import com.golden.website.dataobject.WebsiteUser;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface WebsiteUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbg.generated
     */
    @Insert("insert into website_user (id,loginUserName, state, errorCount, registerTime, sex, name  )values (#{id},#{loginusername}, #{state}, #{errorcount},#{registertime}, #{sex}, #{name})")
    int insert(WebsiteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbg.generated
     */
    WebsiteUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbg.generated
     */
    List<WebsiteUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebsiteUser record);
}