package com.golden.website.dao;

import com.golden.website.dataobject.WebsiteGolden;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface WebsiteGoldenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_golden
     *
     * @mbg.generated
     */
    @Delete("delete from website_golden where id = #{id}")
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_golden
     *
     * @mbg.generated
     */
    @Insert("insert into website_golden (id,title,content,module,createtime) values (#{id},#{title},#{content},#{module},#{createtime})")
    int insert(WebsiteGolden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_golden
     *
     * @mbg.generated
     */
    @Select("select * from website_golden where id = #{id}")
    WebsiteGolden selectByPrimaryKey(String id);
    @Select("select * from website_golden where id = #{id}")
    WebsiteGolden selectByModule(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_golden
     *
     * @mbg.generated
     */
    @Select("select * from website_golden order by module asc")
    List<WebsiteGolden> selectAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_golden
     *
     * @mbg.generated
     */
    @Update("update website_golden set title = #{title},content=#{content}, module= #{module},createtime = #{createtime} where id = #{id} ")
    int updateByPrimaryKey(WebsiteGolden record);
}